# Instalacao das Funcoes ZZ (www.funcoeszz.net)
export ZZOFF=""  # desligue funcoes indesejadas
export ZZPATH="$HOME/.rc/bin/funcoeszz-15.5.sh"  # script
source "$ZZPATH"

# for laptops
synclient TapButton2=2
synclient TapButton3=3

export PATH=$PATH:$HOME/.rc/bin
export PATH=$PATH:$HOME/.bin
export PATH=$PATH:$HOME/bin
alias tasknl='task -contest -weekend'
alias task='tasktime'

alias ls='ls --color --group-directories-first'

source ~/.rvm/scripts/rvm

set -o vi
